api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('', views.index, name='index'),
    path('id/<str:cpv_id>', views.code, name='code')
]

app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('id/<str:cpv_id>', views.code, name='code'),
]

cpv_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('app.urls'))
]

api/models.py
from django.db import models

# Create your models here.
class Code(models.Model):
    objects = models.Manager()

    id = models.CharField(max_length = 10, primary_key=True)
    name = models.CharField(max_length=512)
    parent = models.ForeignKey('self', models.SET_NULL, blank=True, null=True)

app/models.py
from django.db import models

# Create your models here.

api/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.http import HttpResponse, Http404
from django.template import loader
from .models import Code

# Home page with search
def index(request):
    return HttpResponse('Welcome to the API!')

# CPV view (with children)
def code(request, cpv_id: str):
    cpv = get_object_or_404(Code, pk = cpv_id)
    return HttpResponse(f'id : {cpv.id}, name : {cpv.name}')



# TODO: d'habitude j'ai l'habitude d'utiliser une API pour alimenter une vue HTML. En python je fais reposer les vues
#  HTML sur l'API ?

app/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.apps import apps
from django.template import loader
from django.shortcuts import render, get_list_or_404
from api.models import Code
from django.urls import reverse

# Home page with search
def index(request):
    context = {}
    if request.GET and request.GET['text']:
        search_results = Code.objects.filter(name__search=request.GET['text'])
        context = {'search_results': search_results}
    return render(request, 'index.html', context)

# CPV view (with children)
def code(request, cpv_id):
    response = "La page pour le code CPV %s."
    return HttpResponse(response % cpv_id)


# TODO: d'habitude j'ai l'habitude d'utiliser une API pour alimenter une vue HTML. En python je fais reposer les vues
# HTML sur l'API ?

app/templates/index.html
<html>
<head>
    <title>CPV</title>
</head>
<body>
<form action="{% url 'app:index' %}" method="get">
    <legend><h3>Rechercer un code CPV</h3></legend>
    <input type="search" name="text" id="text"/>
    <input type="submit" value="Rechercher"/>
</form>
    {% if search_results|length > 0 %}
        <ul>
        {% for cpv in search_results %}
            <li><a href="{% url 'app:code' cpv.id %}">{{ cpv.id }}: {{ cpv.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Aucune code CPV ne correspond à votre recherche.</p>
    {% endif %}
</body>
</html>